model_name_or_path: /data/horse/ws/hama901h-BFTranslation/checkpoints/Qwen/Qwen3-14B-Base/SFT-sweep/Qwen3-14B-SFT-LR3e-5/
torch_dtype: bfloat16
use_liger_kernel: true
attn_implementation: flash_attention_2
dataset_name: allenai/Dolci-Instruct-DPO
bf16: true
beta: 0.010140377058329894
do_eval: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.6891304247070844e-05
log_level: info
logging_steps: 100
lr_scheduler_type: linear
max_length: 4096
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: /data/horse/ws/hama901h-BFTranslation/checkpoints/Qwen/Qwen3-14B-Base/SFT-sweep-Early-Stop/Qwen3-14B-DPO-BO-EarlyStop-trial014-b0.0101-lr1.69e-05/
overwrite_output_dir: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: true
save_strategy: steps
save_steps: 1000
save_total_limit: 20
seed: 8
warmup_ratio: 0.1
length_normalize_logps: false
max_steps: 600
dataset_test_split_size: 0.005
dataset_test_split_seed: 42
do_train: true
eval_strategy: steps
eval_steps: 100
